evento_festivo_homepage:
    path: /
    defaults: { _controller: 'AppBundle:Evento:index' }

evento_festivo_crear:
    path: /crear
    defaults: { _controller: 'AppBundle:Evento:crear' }

evento_festivo_guardar:
    path: /guardar
    defaults: { _controller: 'AppBundle:Evento:guardar' }
    methods: POST